# ######################################################################
# # COMMON DEFAULTS                                                    #
# ######################################################################

# ----------------------------------------------------------------------
# | PHP                                                                |
# ----------------------------------------------------------------------

PHP: &PHP
    log_errors                  : true
    display_errors              : false
    display_startup_errors      : false
    default_timezone            : 'Europe/Paris'

# ----------------------------------------------------------------------
# | Session (needed for Flash messages or CSRF protection)             |
# ----------------------------------------------------------------------

Session: &Session
    enable                      : false
    name                        : 'Slim3'
    lifetime                    : 0
    path                        : '/'
    domain                      : ''
    secure                      : false
    httponly                    : true
    cache_limiter               : 'nocache'

# ----------------------------------------------------------------------
# | Slim                                                               |
# ----------------------------------------------------------------------

Slim: &Slim
    displayErrorDetails         : false

# ----------------------------------------------------------------------
# | Security                                                           |
# ----------------------------------------------------------------------

Security: &Security
    enable_csrf_token_persistence: false

# ----------------------------------------------------------------------
# | Monolog                                                            |
# ----------------------------------------------------------------------

Monolog: &Monolog
    loggerName                  : 'Slim3'
    StreamHandler: &StreamHandler
        enable                  : true
        logLevel                : DEBUG
    NativeMailerHandler: &NativeMailerHandler
        enable                  : false
        logLevel                : ERROR
        to                      : ''
        subject                 : 'Error'
        from                    : ''

# ----------------------------------------------------------------------
# | Twig                                                               |
# ----------------------------------------------------------------------

# http://twig.sensiolabs.org/doc/api.html

Twig: &Twig
    debug                       : false
    cache                       : true
    auto_reload                 : true
    strict_variables            : true

# ----------------------------------------------------------------------
# | Application                                                        |
# ----------------------------------------------------------------------

App: &App
    language_code               : 'en'

    metas:
        title                   : 'Slim 3 Skeleton'
        title_separator         : ' - '
        description             : ""

    # false or Google Analytics ID 'UA-XXXXX-Y'
    google_analytics_id         : false

# ######################################################################
# # ENVIRONMENT SPECIFIC                                               #
# ######################################################################

# ----------------------------------------------------------------------
# | Development                                                        |
# ----------------------------------------------------------------------

development:
    PHP:
        <<: *PHP
        display_errors          : true
        display_startup_errors  : true

    Session:
        <<: *Session

    Slim:
        <<: *Slim
        displayErrorDetails     : true

    Security:
        <<: *Security

    Monolog:
        <<: *Monolog

    Twig:
        <<: *Twig
        debug                   : true

    App:
        <<: *App

# ----------------------------------------------------------------------
# | Production                                                         |
# ----------------------------------------------------------------------

production:
    PHP:
        <<: *PHP

    Session:
        <<: *Session

    Slim:
        <<: *Slim

    Security:
        <<: *Security

    Monolog:
        <<: *Monolog
        StreamHandler:
            <<: *StreamHandler
            logLevel            : WARNING
        NativeMailerHandler:
            <<: *NativeMailerHandler
            enable              : true

    Twig:
        <<: *Twig

    App:
        <<: *App
