# ######################################################################
# # COMMON DEFAULTS                                                    #
# ######################################################################

# ----------------------------------------------------------------------
# | PHP                                                                |
# ----------------------------------------------------------------------

PHP: &PHP
    log_errors                  : true
    display_errors              : false
    display_startup_errors      : false
    default_timezone            : 'Europe/Paris'

# ----------------------------------------------------------------------
# | Session (needed for Flash messages or CSRF protection)             |
# ----------------------------------------------------------------------

# https://github.com/akrabat/rka-slim-session-middleware/blob/master/RKA/SessionMiddleware.php
Session: &Session
    enable                      : false
    name                        : 'Slim3Skeleton'
    lifetime                    : 0
    path                        : '/'
    domain                      : ''
    secure                      : false
    httponly                    : true
    cache_limiter               : 'nocache'

# ----------------------------------------------------------------------
# | Slim                                                               |
# ----------------------------------------------------------------------

# https://www.slimframework.com/docs/objects/application.html

Slim: &Slim
    display_error_details       : false
    use_router_cache         : false

# ----------------------------------------------------------------------
# | Security                                                           |
# ----------------------------------------------------------------------

Security: &Security
    enable_csrf_token_persistence: false

# ----------------------------------------------------------------------
# | Monolog                                                            |
# ----------------------------------------------------------------------

Monolog: &Monolog
    logger_name                  : 'Slim3'
    StreamHandler: &StreamHandler
        enable                  : true
        level                : DEBUG
    NativeMailerHandler: &NativeMailerHandler
        enable                  : false
        level                : ERROR
        to                      : ''
        subject                 : 'Error'
        from                    : { 'no-reply@localhost.com': 'Slim 3 Skeleton' }
    SwiftMailerHandler: &SwiftMailerHandler
        enable                  : false
        level                : ERROR
        to                      : ''
        subject                 : 'Error'
        from                    : { 'no-reply@localhost.com': 'Slim 3 Skeleton' }

# ----------------------------------------------------------------------
# | Twig                                                               |
# ----------------------------------------------------------------------

# http://twig.sensiolabs.org/doc/api.html

Twig: &Twig
    debug                       : false
    cache                       : true
    auto_reload                 : true
    strict_variables            : true

# ----------------------------------------------------------------------
# | Swift Mailer                                                       |
# ----------------------------------------------------------------------

# http://swiftmailer.org/docs/sending.html

SwiftMailer: &SwiftMailer
    # smtp, sendmail, false
    transport                   : smtp
    auth_mode                   : ''
    username                    : ''
    password                    : ''
    host                        : ''
    port                        : ''
    encryption                  : ''
    command                     : null

# ----------------------------------------------------------------------
# | Application                                                        |
# ----------------------------------------------------------------------

App: &App
    language_code               : 'en'

    metas:
        title                   : 'Slim 3 Skeleton'
        title_separator         : ' - '
        description             : ""

    # false or Google Analytics ID 'UA-XXXXX-Y'
    google_analytics_id         : false

# ######################################################################
# # ENVIRONMENT SPECIFIC                                               #
# ######################################################################

# ----------------------------------------------------------------------
# | Development                                                        |
# ----------------------------------------------------------------------

development:
    PHP:
        <<: *PHP
        display_errors          : true
        display_startup_errors  : true

    Session:
        <<: *Session

    Slim:
        <<: *Slim
        display_error_details   : true

    Security:
        <<: *Security

    Monolog:
        <<: *Monolog

    Twig:
        <<: *Twig
        debug                   : true

    SwiftMailer:
        <<: *SwiftMailer

    App:
        <<: *App

# ----------------------------------------------------------------------
# | Production                                                         |
# ----------------------------------------------------------------------

production:
    PHP:
        <<: *PHP

    Session:
        <<: *Session

    Slim:
        <<: *Slim
        use_router_cache     : true

    Security:
        <<: *Security

    Monolog:
        <<: *Monolog
        StreamHandler:
            <<: *StreamHandler
            level            : WARNING
        SwiftMailerHandler:
            <<: *SwiftMailerHandler
            enable              : true

    Twig:
        <<: *Twig

    SwiftMailer:
        <<: *SwiftMailer

    App:
        <<: *App
