# ######################################################################
# # COMMON DEFAULTS                                                    #
# ######################################################################

# ----------------------------------------------------------------------
# | PHP                                                                |
# ----------------------------------------------------------------------

php: &php
    log_errors: true
    display_errors: false
    display_startup_errors: false
    default_timezone: 'Europe/Paris'

# ----------------------------------------------------------------------
# | Session (needed for Flash messages or CSRF protection)             |
# ----------------------------------------------------------------------

# https://github.com/akrabat/rka-slim-session-middleware/blob/master/RKA/SessionMiddleware.php

session: &session
    enable: false
    name: 'Slim3Skeleton'
    lifetime: 0
    path: '/'
    domain: ''
    secure: false
    httponly: true
    cache_limiter: 'nocache'

# ----------------------------------------------------------------------
# | Slim                                                               |
# ----------------------------------------------------------------------

# https://www.slimframework.com/docs/objects/application.html

slim: &slim
    display_error_details: false
    use_router_cache: false

# ----------------------------------------------------------------------
# | Security                                                           |
# ----------------------------------------------------------------------

security: &security
    enable_csrf_token_persistence: false

# ----------------------------------------------------------------------
# | Monolog                                                            |
# ----------------------------------------------------------------------

# https://github.com/Seldaek/monolog/blob/master/doc/02-handlers-formatters-processors.md

monolog: &monolog
    logger_name: 'Slim3Skeleton'

    StreamHandler: &StreamHandler
        enable: true
        level: DEBUG

    NativeMailerHandler: &NativeMailerHandler
        enable: false
        level: ERROR
        to: ''
        subject: 'Slim 3 Skeleton Error'
        from: { 'no-reply@localhost.com': 'Slim 3 Skeleton' }

    SwiftMailerHandler: &SwiftMailerHandler
        enable: false
        level: ERROR
        to: ''
        subject: 'Slim 3 Skeleton Error'
        from: { 'no-reply@localhost.com': 'Slim 3 Skeleton' }

# ----------------------------------------------------------------------
# | Twig                                                               |
# ----------------------------------------------------------------------

# http://twig.sensiolabs.org/doc/api.html

twig: &twig
    debug: false
    use_cache: true
    auto_reload: true
    strict_variables: true

# ----------------------------------------------------------------------
# | Swift Mailer                                                       |
# ----------------------------------------------------------------------

# http://swiftmailer.org/docs/sending.html

swiftmailer: &swiftmailer
    enable: false
    # smtp or sendmail
    transport_type: 'smtp'

    smtp:
        auth_mode: ''
        username: ''
        password: ''
        host: ''
        port: ''
        encryption: ''

    sendmail:
        command: ''

# ----------------------------------------------------------------------
# | Application                                                        |
# ----------------------------------------------------------------------

app: &app
    language_code: 'en'

    metas:
        title: 'Slim 3 Skeleton'
        title_separator: ' - '
        description: ""

    # false or Google Analytics ID 'UA-XXXXX-Y'
    google_analytics_id: false

# ######################################################################
# # ENVIRONMENT SPECIFIC                                               #
# ######################################################################

# ----------------------------------------------------------------------
# | Development                                                        |
# ----------------------------------------------------------------------

development:
    php:
        <<: *php
        display_errors: true
        display_startup_errors: true

    session:
        <<: *session

    slim:
        <<: *slim
        display_error_details: true

    security:
        <<: *security

    monolog:
        <<: *monolog

    twig:
        <<: *twig
        debug: true

    swiftmailer:
        <<: *swiftmailer

    app:
        <<: *app

# ----------------------------------------------------------------------
# | Production                                                         |
# ----------------------------------------------------------------------

production:
    php:
        <<: *php

    session:
        <<: *session

    slim:
        <<: *slim
        use_router_cache: true

    security:
        <<: *security

    monolog:
        <<: *monolog
        StreamHandler:
            <<: *StreamHandler
            level: WARNING
        SwiftMailerHandler:
            <<: *SwiftMailerHandler
            enable: true

    twig:
        <<: *twig

    swiftmailer:
        <<: *swiftmailer

    app:
        <<: *app
